manifest:
  remotes:
    - name: PraeceptorXS
      url-base: https://github.com/PraeceptorXS
  projects:
    - name: zmk
      remote: PraeceptorXS
      revision: main
      import: app/west.yml
  self:
    path: config
